//package com.example.cinemaatl
//
//<?xml version="1.0" encoding="utf-8"?>
//<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
//xmlns:tools="http://schemas.android.com/tools"
//android:layout_width="match_parent"
//android:layout_height="match_parent"
//xmlns:app="http://schemas.android.com/apk/res-auto"
//android:background="@color/black"
//tools:context=".fragments.SeatsFragment">
//
//<ImageView
//android:id="@+id/btBack"
//android:layout_width="wrap_content"
//android:layout_height="wrap_content"
//android:src="@drawable/back_2"
//app:layout_constraintStart_toStartOf="parent"
//app:layout_constraintTop_toTopOf="parent"
//android:layout_margin="40dp"/>
//
//
//<TextView
//android:id="@+id/tvSelected"
//android:layout_width="wrap_content"
//android:layout_height="wrap_content"
//android:textStyle="bold"
//android:textSize="19sp"
//android:textColor="@color/white"
//app:layout_constraintStart_toStartOf="parent"
//app:layout_constraintEnd_toEndOf="parent"
//app:layout_constraintTop_toTopOf="parent"
//android:layout_margin="40dp"
//
//android:text="Selected Seats" />
//
//
//<androidx.recyclerview.widget.RecyclerView
//android:id="@+id/dateRecyclerView"
//android:layout_width="match_parent"
//android:layout_height="0dp"
//app:layout_constraintTop_toBottomOf="@id/tvSelected"
//app:layout_constraintStart_toStartOf="parent"
//app:layout_constraintEnd_toEndOf="parent"
//app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
//android:orientation="vertical"
//android:paddingStart="8dp"
//android:paddingEnd="8dp"
//android:layout_marginTop="8dp"
//android:layout_marginBottom="8dp"
//android:clipToPadding="false"/>
//
//<androidx.recyclerview.widget.RecyclerView
//android:id="@+id/timeRecyclerView"
//android:layout_width="match_parent"
//android:layout_height="0dp"
//app:layout_constraintTop_toBottomOf="@id/dateRecyclerView"
//app:layout_constraintStart_toStartOf="parent"
//app:layout_constraintEnd_toEndOf="parent"
//app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager"
//android:orientation="vertical"
//android:paddingStart="8dp"
//android:paddingEnd="8dp"
//android:layout_marginTop="8dp"
//android:layout_marginBottom="8dp"
//android:clipToPadding="false"/>
//
//<ImageView
//android:id="@+id/cinemaView"
//android:layout_width="wrap_content"
//android:layout_height="wrap_content"
//android:src="@drawable/cinema"
//app:layout_constraintTop_toBottomOf="@id/timeRecyclerView"
//app:layout_constraintStart_toStartOf="parent"
//app:layout_constraintEnd_toEndOf="parent"/>
//
//<androidx.recyclerview.widget.RecyclerView
//android:id="@+id/rvSeats"
//android:layout_width="match_parent"
//android:layout_height="wrap_content"
//app:layoutManager="androidx.recyclerview.widget.GridLayoutManager"
//app:spanCount="7"
//android:layout_marginStart="48dp"
//android:layout_marginTop="48dp"
//android:layout_marginEnd="48dp"
//app:layout_constraintTop_toTopOf="@id/cinemaView"
//app:layout_constraintStart_toStartOf="@id/cinemaView"
//app:layout_constraintBottom_toBottomOf="@id/cinemaView"
//
///>
//
//<LinearLayout
//android:id="@+id/ticketState"
//android:layout_width="match_parent"
//android:layout_height="0dp"
//android:gravity="center"
//android:layout_marginStart="40dp"
//app:layout_constraintStart_toStartOf="parent"
//app:layout_constraintEnd_toEndOf="parent"
//app:layout_constraintTop_toBottomOf="@id/cinemaView"
//android:layout_marginEnd="40dp"
//android:orientation="horizontal">
//
//<View
//android:layout_width="10dp"
//android:layout_height="10dp"
//android:background="@drawable/ic_seat_aviable"/>
//<TextView
//android:layout_width="wrap_content"
//android:layout_height="wrap_content"
//android:layout_weight="1"
//android:layout_marginStart="8dp"
//android:textColor="@color/white"
//android:textSize="12sp"
//android:text="Aviable"/>
//
//<View
//android:layout_width="10dp"
//android:layout_height="10dp"
//android:background="@drawable/ic_seat_selected"/>
//<TextView
//android:layout_width="wrap_content"
//android:layout_height="wrap_content"
//android:layout_weight="1"
//android:textColor="@color/white"
//android:textSize="12sp"
//android:text="Selected"/>
//<View
//android:layout_width="10dp"
//android:layout_height="10dp"
//android:background="@drawable/ic_seat_unaviable"/>
//
//<TextView
//android:layout_width="wrap_content"
//android:layout_height="wrap_content"
//android:layout_weight="1"
//android:textColor="@color/white"
//android:textSize="12sp"
//android:text="Unaviable"/>
//
//</LinearLayout>
//<androidx.appcompat.widget.AppCompatButton
//android:layout_width="200dp"
//android:layout_height="wrap_content"
//android:background="@drawable/orange_bg"
//app:layout_constraintTop_toBottomOf="@id/ticketState"
//app:layout_constraintEnd_toEndOf="parent"
//android:layout_marginEnd="8dp"
//
//android:layout_marginTop="8dp"
//android:text="Download Ticket"
//android:textColor="@color/white"
//app:layout_constraintBottom_toBottomOf="parent"
//android:layout_marginBottom="80dp"/>
//
//
//
//
//</androidx.constraintlayout.widget.ConstraintLayout>